### PR TITLE
fix relative path names

### PR DESCRIPTION
**Pull request by mightbxg**
1. Fix relative path names "./", in case current working directory is not "./".
2. Move configuration file and history record file to the path where dropbox_uploader.sh is.

### CODE REVIEW

**Comment by andreafabrizi** [comment]
Why move configuration file and history record file to the path where dropbox_uploader.sh is? By default are in the home folder.

**Comment by mightbxg** [comment]
Because it can make home folder clean and files related to this script  easier to be removed. Just personal preference.

**Comment by westhouseit** [comment]
@mightbxg, how about instead adding a working directory variable that defaults to the home dir as then you can have what you want without introducing a change that is likely to be rejected?

**Comment by mightbxg** [comment]
@westhouseit I don't really care that much, it's just an advice for the author.

**Pull request closed without merging**
