### PR TITLE
Make use of refresh tokens

### PR DESCRIPTION
**Pull request by Terge3141**
Dear Andrea,
as you probably already know, dropbox changed their authorization method. See issue "Will Dropbox uploader be updated for new api?", 515.
My pull request handles the new authorization method.

Best regards,

Michael

### CODE REVIEW

**Comment by asanakoy** [comment]
What about the rest of the API? did it stay the same?

**Comment by andreafabrizi** [comment]
Thanks Michael!

**Comment by Terge3141** [comment]
> What about the rest of the API? did it stay the same?

As far as I understand, the rest of the API that Dropbox-Uploader uses stays the same.

**Comment by kajan001** [comment]
Thanks! 👍👍👍

**Comment by tjluoma** [comment]
Does this mean we are going to have to regenerate tokens from time to time?

**Comment by Terge3141** [comment]
> Does this mean we are going to have to regenerate tokens from time to time?
No:: The access token is generated from the request token. The request token is generated once in the initial setup.

**Pull request merged**
